// export const host = "https://socket-chat-app.up.railway.app";
export const host = "http://localhost:8000";
export const RegisterRoute = host + "/api/auth/register";
export const LoginRoute = host + "/api/auth/login";
export const avatarApiRoutePrefix = "https://api.multiavatar.com/";
export const getAllUsersRoutePrefix = host + "/api/auth/getAllUsers/";
export const addMessageRoute = host + "/api/messages/addMessage";
export const getMessagesRoute = host + "/api/messages/getMessages";
export const getOnlineUsers = host + "/api/getOnlineUsers";
